# Generated by Django 5.2.4 on 2025-08-09 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Telefon numarası '05xxxxxxxxx' formatında, 11 haneli ve sadece sayılardan oluşmalıdır.", regex='^\\d{11}$')]),
        ),
    ]
