# Generated by Django 5.2.4 on 2025-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
